name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build powershell GUI to EXE
        run: |
          Install-Module ps2exe -Force -Scope CurrentUser
          Invoke-ps2exe -inputFile "RealtimeSyncStarter.ps1" -outputFile "RealtimeSyncStarter.exe" -noConsole
        shell: pwsh

      - name: Upload compiled EXE
        uses: actions/upload-artifact@v4
        with:
          name: RealtimeSyncStarter
          path: RealtimeSyncStarter.exe
